export enum SpecialistTypes {
  ZOOTECNICO = 'ZOOTÉCNICO',
  AGRONOMO = 'AGRÔNOMO',
  ENGFLORESTAL = 'ENG. FLORESTAL',
  VETERINARIO = 'VETERINÁRIO',
  PECUARISTA = 'PECUARISTA',
  AQUICULTOR = 'AQUICULTOR',
  AVICULTOR = 'AVICULTOR',
  APICULTOR = 'APICULTOR',
}
