export enum ExpertType {
  ZOOTECNICO = 'ZOOTECNICO',
  AGRONOMO = 'AGRONOMO',
  ENGFLORESTAL = 'ENGENHEIRO FLORESTAL',
  VETERINARIO = 'VETERINARIO',
  PECUARISTA = 'PECUARISTA',
  AQUICULTOR = 'AQUICULTOR',
  AVICULTOR = 'AVICULTOR',
  APICULTOR = 'APICULTOR',
}
